cargo-features = ["resolver"]

[workspace]
members = [
	"auction",
	"authority",
	"bencher",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/rpc",
	"oracle/rpc/runtime-api",
	"tokens",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xcm",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
	"weight-gen",
	"weight-meter",
]
resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[patch.'https://github.com/paritytech/substrate']
frame-benchmarking = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
frame-support = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
frame-system = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-authorship = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-balances = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-elections-phragmen = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-offences = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-scheduler = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-session = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-staking = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-timestamp = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-treasury = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
pallet-vesting = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sc-client-api = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sc-client-db = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sc-executor = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sc-executor-common = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sc-executor-wasmi = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-api = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-application-crypto = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-arithmetic = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-authorship = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-blockchain = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-consensus = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-core = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-debug-derive = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-externalities = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-inherents = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-io = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-keystore = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-npos-elections = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-panic-handler = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-runtime = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-runtime-interface = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-session = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-staking = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-state-machine = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-std = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-storage = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-tasks = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-timestamp = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-trie = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-version = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-wasm-interface = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }
sp-utils = { git = "https://github.com/paritytech//substrate", rev = "58f0223a75933e3226f330b8458bcb78e12164cf" }

[patch.'https://github.com/paritytech/cumulus']
cumulus-primitives-core = { git = "https://github.com/paritytech//cumulus", rev = "fa116cfbfb470a8114fc02f9d2e3c0a5ab6c7193" }
parachain-info = { git = "https://github.com/paritytech//cumulus", rev = "fa116cfbfb470a8114fc02f9d2e3c0a5ab6c7193" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech//cumulus", rev = "fa116cfbfb470a8114fc02f9d2e3c0a5ab6c7193" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech//cumulus", rev = "fa116cfbfb470a8114fc02f9d2e3c0a5ab6c7193" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech//cumulus", rev = "fa116cfbfb470a8114fc02f9d2e3c0a5ab6c7193" }

[patch.'https://github.com/paritytech/polkadot']
xcm = { git = "https://github.com/paritytech//polkadot", rev = "d348ba982f823adeb700b54db98169520f323595" }
xcm-executor = { git = "https://github.com/paritytech//polkadot", rev = "d348ba982f823adeb700b54db98169520f323595" }
xcm-builder = { git = "https://github.com/paritytech//polkadot", rev = "d348ba982f823adeb700b54db98169520f323595" }
pallet-xcm = { git = "https://github.com/paritytech//polkadot", rev = "d348ba982f823adeb700b54db98169520f323595" }
polkadot-core-primitives = { git = "https://github.com/paritytech//polkadot", rev = "d348ba982f823adeb700b54db98169520f323595" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech//polkadot", rev = "d348ba982f823adeb700b54db98169520f323595" }
polkadot-parachain = { git = "https://github.com/paritytech//polkadot", rev = "d348ba982f823adeb700b54db98169520f323595" }
polkadot-primitives = { git = "https://github.com/paritytech//polkadot", rev = "d348ba982f823adeb700b54db98169520f323595" }
xcm-simulator = { git = "https://github.com/paritytech//polkadot", rev = "d348ba982f823adeb700b54db98169520f323595" }
