[workspace]
members = [
	"asset-registry",
	"auction",
	"authority",
	"bencher",
	"bencher/test",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/rpc",
	"oracle/rpc/runtime-api",
	"tokens",
	"tokens/rpc",
	"tokens/rpc/runtime-api",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xcm",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
	"weight-gen",
	"weight-meter",
	"payments"
]

exclude = ["bencher/test"]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[patch.'https://github.com/PureStake/substrate']
frame-benchmarking = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
frame-support = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
frame-system = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-authority-discovery = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-authorship = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-babe = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-balances = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-elections-phragmen = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-scheduler = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-session = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-staking = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-timestamp = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-treasury = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-vesting = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
pallet-transaction-payment = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sc-client-api = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sc-client-db = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sc-executor = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sc-executor-common = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sc-utils = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-api = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-application-crypto = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-arithmetic = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-authority-discovery = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-blockchain = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-consensus = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-consensus-slots = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-core = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-debug-derive = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-externalities = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-inherents = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-io = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-keystore = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-npos-elections = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-panic-handler = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-runtime = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-runtime-interface = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-session = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-staking = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-state-machine = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-std = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-storage = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-timestamp = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-trie = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-version = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-wasm-interface = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-tracing = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-maybe-compressed-blob = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }
sp-weights = { git = "https://github.com/PureStake//substrate", rev = "a2037bdedef0aa812017efee1d0fa63d4f5fcbae" }

[patch.'https://github.com/PureStake/cumulus']
cumulus-primitives-core = { git = "https://github.com/PureStake//cumulus", rev = "761dd1d008186184f59cb9fadb33278847cec625" }
cumulus-pallet-dmp-queue = { git = "https://github.com/PureStake//cumulus", rev = "761dd1d008186184f59cb9fadb33278847cec625" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/PureStake//cumulus", rev = "761dd1d008186184f59cb9fadb33278847cec625" }
cumulus-pallet-xcm = { git = "https://github.com/PureStake//cumulus", rev = "761dd1d008186184f59cb9fadb33278847cec625" }
parachain-info = { git = "https://github.com/PureStake//cumulus", rev = "761dd1d008186184f59cb9fadb33278847cec625" }

[patch.'https://github.com/PureStake/polkadot']
pallet-xcm = { git = "https://github.com/PureStake//polkadot", rev = "ed18fe73c1b4dd6709bed996d2d06a0e55a002a7" }
polkadot-core-primitives = { git = "https://github.com/PureStake//polkadot", rev = "ed18fe73c1b4dd6709bed996d2d06a0e55a002a7" }
polkadot-runtime-parachains = { git = "https://github.com/PureStake//polkadot", rev = "ed18fe73c1b4dd6709bed996d2d06a0e55a002a7" }
polkadot-parachain = { git = "https://github.com/PureStake//polkadot", rev = "ed18fe73c1b4dd6709bed996d2d06a0e55a002a7" }
polkadot-primitives = { git = "https://github.com/PureStake//polkadot", rev = "ed18fe73c1b4dd6709bed996d2d06a0e55a002a7" }
xcm = { git = "https://github.com/PureStake//polkadot", rev = "ed18fe73c1b4dd6709bed996d2d06a0e55a002a7" }
xcm-executor = { git = "https://github.com/PureStake//polkadot", rev = "ed18fe73c1b4dd6709bed996d2d06a0e55a002a7" }
xcm-builder = { git = "https://github.com/PureStake//polkadot", rev = "ed18fe73c1b4dd6709bed996d2d06a0e55a002a7" }
xcm-simulator = { git = "https://github.com/PureStake//polkadot", rev = "ed18fe73c1b4dd6709bed996d2d06a0e55a002a7" }